### ISSUE TITLE
Can't set attributes containing %

### ISSUE THREAD

**Issue by discordianfish** [byxorna/collins-cli#13]
Hi,

looks like the attribute values gets interpreted as format string somehow:

```
$ collins modify -t "$tag" -a "test:%"
precision given twice

$ collins modify -t "$tag" -a "test:something where % is contained"
too few arguments
```

It looks like the client isn't doing anything special, so I suspect a issue with collins-client but couldn't find anything obvious. I'll try to reproduce this with only collins-client tomorrow and will move issue if it's a upstream problem.

**Comment by discordianfish** [comment]
@byxorna FYI

**Comment by byxorna** [comment]
@discordianfish thanks, eager to see what you find!
